export let products = [
  {
    id: 1,
    title: "Camiseta Local de Argentina - 2023",
    price: 3500,
    description: "Camiseta oficial local de la selección argentina de fútbol.",
    img: "https://res.cloudinary.com/drzbbyfbt/image/upload/v1707789103/ecommerce-react/download_hseg0v.jpg",
    stock: 20,
    category: "Selecciones",
  },
  {
    id: 2,
    title: "Camiseta Local de Boca Juniors - 2024",
    price: 4500,
    description: "Camiseta oficial local de Boca Juniors, uno de los principales clubes de fútbol de Argentina.",
    img: "ejemplo.jpg",
    stock: 15,
    category: "Clubes",
  },
  {
    id: 3,
    title: "Camiseta Local de Brasil - 2023",
    price: 3000,
    description: "Camiseta oficial local de la selección brasileña de fútbol.",
    img: "ejemplo.jpg",
    stock: 25,
    category: "Selecciones",
  },
  {
    id: 4,
    title: "Camiseta Visitante de Real Madrid - 2024",
    price: 5000,
    description: "Camiseta oficial visitante del Real Madrid, uno de los principales clubes de fútbol del mundo.",
    img: "ejemplo.jpg",
    stock: 10,
    category: "Clubes",
  },
  {
    id: 5,
    title: "Camiseta Local de Manchester United - 2024",
    price: 4800,
    description: "Camiseta oficial local del Manchester United, uno de los clubes de fútbol más populares del mundo.",
    img: "ejemplo.jpg",
    stock: 18,
    category: "Clubes",
  },
  {
    id: 6,
    title: "Pulsera de Silicona Argentina",
    price: 500,
    description: "Pulsera de silicona con los colores y el escudo de la selección argentina de fútbol.",
    img: "ejemplo.jpg",
    stock: 50,
    category: "Accesorios",
  },
  {
    id: 7,
    title: "Bufanda de Boca Juniors",
    price: 1200,
    description: "Bufanda oficial de Boca Juniors, perfecta para los días de frío en la cancha.",
    img: "ejemplo.jpg",
    stock: 30,
    category: "Accesorios",
  },
  {
    id: 8,
    title: "Pulsera de Brasil",
    price: 500,
    description: "Pulsera con los colores y el escudo de la selección brasileña de fútbol.",
    img: "ejemplo.jpg",
    stock: 50,
    category: "Accesorios",
  },
  {
    id: 9,
    title: "Gorra Real Madrid",
    price: 1500,
    description: "Gorra oficial del Real Madrid, ideal para lucir en los partidos.",
    img: "ejemplo.jpg",
    stock: 20,
    category: "Accesorios",
  },
  {
    id: 10,
    title: "Bufanda Manchester United",
    price: 1000,
    description: "Bufanda oficial del Manchester United para mantenerte abrigado en los encuentros.",
    img: "ejemplo.jpg",
    stock: 25,
    category: "Accesorios",
  },
];
