export let products = [
  {
    id: 1,
    title: "Camiseta Local de Argentina - 2023",
    price: 50000,
    description: "Camiseta oficial local de la selección argentina de fútbol.",
    img: "https://res.cloudinary.com/drzbbyfbt/image/upload/v1708034458/ecommerce-react/Argentina2023.webp",
    stock: 20,
    category: "Selecciones",
  },
  {
    id: 2,
    title: "Camiseta Local de Boca Juniors - 2024",
    price: 45000,
    description: "Camiseta oficial local de Boca Juniors, marca Adidas.",
    img: "https://res.cloudinary.com/drzbbyfbt/image/upload/v1708034458/ecommerce-react/Boca2024.jpg",
    stock: 15,
    category: "Clubes",
  },
  {
    id: 3,
    title: "Camiseta Local de Brasil - 2023",
    price: 35000,
    description: "Camiseta oficial local de la selección brasileña de fútbol.",
    img: "https://res.cloudinary.com/drzbbyfbt/image/upload/v1708034462/ecommerce-react/brasil2023.png",
    stock: 25,
    category: "Selecciones",
  },
  {
    id: 4,
    title: "Camiseta Local de Real Madrid - 2024",
    price: 60000,
    description: "Camiseta oficial local del Real Madrid, marca Adidas",
    img: "https://res.cloudinary.com/drzbbyfbt/image/upload/v1708034458/ecommerce-react/Realmadrid2024.avif",
    stock: 10,
    category: "Clubes",
  },
  {
    id: 5,
    title: "Camiseta Local de Manchester United - 2024",
    price: 48000,
    description: "Camiseta oficial local del Manchester United, marca Adidas",
    img: "https://res.cloudinary.com/drzbbyfbt/image/upload/v1708034719/ecommerce-react/MU2024.avif",
    stock: 18,
    category: "Clubes",
  },
  {
    id: 6,
    title: "Pulsera de Silicona Argentina",
    price: 2500,
    description: "Pulsera de silicona con los colores y la bandera argentina.",
    img: "https://res.cloudinary.com/drzbbyfbt/image/upload/v1708034788/ecommerce-react/pulseraArg.webp",
    stock: 50,
    category: "Accesorios",
  },
  {
    id: 7,
    title: "Bufanda de Boca Juniors",
    price: 8000,
    description: "Bufanda oficial de Boca Juniors, perfecta para los días de frío en la cancha.",
    img: "https://res.cloudinary.com/drzbbyfbt/image/upload/v1708034852/ecommerce-react/BufandaBoca.webp",
    stock: 30,
    category: "Accesorios",
  },
  {
    id: 8,
    title: "Gorra de Brasil",
    price: 5000,
    description: "Gorra con los colores y el escudo de la selección brasileña de fútbol.",
    img: "https://res.cloudinary.com/drzbbyfbt/image/upload/v1708034969/ecommerce-react/gorrabrasil.webp",
    stock: 50,
    category: "Accesorios",
  },
  {
    id: 9,
    title: "Gorra Real Madrid",
    price: 15000,
    description: "Gorra oficial del Real Madrid, ideal para lucir en los partidos.",
    img: "https://res.cloudinary.com/drzbbyfbt/image/upload/v1708035020/ecommerce-react/gorraRealMadrid.jpg",
    stock: 20,
    category: "Accesorios",
  },
  {
    id: 10,
    title: "Bufanda Manchester United",
    price: 9000,
    description: "Bufanda oficial del Manchester United para mantenerte abrigado en los encuentros.",
    img: "https://res.cloudinary.com/drzbbyfbt/image/upload/v1708035077/ecommerce-react/bufandaMU.jpg",
    stock: 25,
    category: "Accesorios",
  },
];
